In [29]:
# Packages
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
import datetime
#from All_data_muduo import df,f1
#//*** Use the whole window in the IPYNB editor
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

#//*** Maximize columns and rows displayed by pandas
# pd.set_option('display.max_rows', 1000)
# pd.set_option('display.max_columns',20 )

Look at Sparse PCA
https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.SparsePCA.html

In [30]:
"""
import pandas as pd

input_file1 = "./ignore_folder/processed_reddit_v4_1min_amc_stock_comments.csv.zip"

input_file2 = "./ignore_folder/processed_reddit_v4_1min_tfidf_matrix.pkl"
input_file3 = "./ignore_folder/processed_reddit_v4_1min_tfidf.pkl"

f1 = pd.read_csv(input_file1)
f2 = pd.read_pickle(input_file2)
#df = pd.DataFrame(f2.toarray(),index = f1["time"])
#f1 = f1.drop("token", axis = 1)

#df["price"] = (f1["open"].values + f1["close"].values + f1["high"].values + f1["low"].values)/4
"""

'\nimport pandas as pd\n\ninput_file1 = "./ignore_folder/processed_reddit_v4_1min_amc_stock_comments.csv.zip"\n\ninput_file2 = "./ignore_folder/processed_reddit_v4_1min_tfidf_matrix.pkl"\ninput_file3 = "./ignore_folder/processed_reddit_v4_1min_tfidf.pkl"\n\nf1 = pd.read_csv(input_file1)\nf2 = pd.read_pickle(input_file2)\n#df = pd.DataFrame(f2.toarray(),index = f1["time"])\n#f1 = f1.drop("token", axis = 1)\n\n#df["price"] = (f1["open"].values + f1["close"].values + f1["high"].values + f1["low"].values)/4\n'

In [ ]:
#df = pd.DataFrame(f2.todense(),index = f1["time"])

In [62]:
#%%
import pandas as pd

input_file1 = "./ignore_folder/processed_reddit_v4_1min_amc_stock_comments.csv.zip"

input_file2 = "./ignore_folder/processed_reddit_v4_1min_tfidf_matrix.pkl"

f1 = pd.read_csv(input_file1)
X = pd.read_pickle(input_file2)

S1 = pd.Series((f1["open"].values+ f1["close"].values+ f1["high"].values + f1["low"].values)/4)

lst = []
lst.extend(S1[1:])
lst.append(lst[-1])
y = (S1/pd.Series(lst))-1

# %%
from sklearn.decomposition import PCA

pca = PCA(n_components="mle")
#pca.fit_transform(X,y)
# %%
from sklearn.decomposition import TruncatedSVD
tsvd = TruncatedSVD(100)
X = tsvd.fit_transform(X,y)
# %%
X.shape
# %%
df = pd.DataFrame(X)
df["y"] = y
# %%
df.shape
# %%
#df.to_csv("1min_for_ML _00_feat")

(305098, 101)

In [26]:
f1

,Unnamed: 0,time,open,high,low,close,volume,token
0,0,2019-07-24 09:00:00,4.090000,4.090000,4.090000,4.090000,406,"['index', 'fund', 'tracks', 'performance', 'st..."
1,1,2019-07-24 09:31:00,9.846181,9.912903,9.846181,9.912903,23448,[]
2,2,2019-07-24 09:32:00,9.922435,9.951029,9.922435,9.922435,3394,[]
3,3,2019-07-24 09:33:00,9.939591,9.998688,9.935302,9.998688,24294,[]
4,4,2019-07-24 09:34:00,10.003453,10.017751,9.874776,9.960561,67195,[]
...,...,...,...,...,...,...,...,...
305093,305093,2021-07-12 19:56:00,41.250000,41.290000,41.220000,41.290000,10274,[]
305094,305094,2021-07-12 19:57:00,41.270000,41.350000,41.250000,41.330000,6832,[]
305095,305095,2021-07-12 19:58:00,41.330000,41.330000,41.250000,41.250000,14056,[]
305096,305096,2021-07-12 19:59:00,41.250000,41.280000,41.250000,41.250000,8974,[]
305097,305097,2021-07-12 20:00:00,41.250000,41.340000,41.250000,41.280000,11989,[]

In [78]:
f1 = pd.read_csv(input_file1)
f1 = f1[f1.columns[1:]]
for x in [1,2,5,15,30,60,180,450,1440,2880]:
    #print(f1['close'][-x:])
    #f1[f"close_{x}"] = list(f1['close'][x:]) + list(f1['close'][:x].to_numpy())
    #print(len(f1),len(list(f1['close'][x:])),len(list(f1['close'][:x])))
    #print(list(np.empty( len(f1)-x )))
    
    nan_list = list(np.empty( x )* np.nan )

    f1[f"close_{x}"] = list(f1['close'][x:]) + nan_list 

f1.tail(50)

,time,open,high,low,close,volume,token,close_1,close_2,close_5,close_15,close_30,close_60,close_180,close_450,close_1440,close_2880
305048,2021-07-12 19:11:00,41.6200,41.620,41.6000,41.6000,5486,[],41.5500,41.5300,41.5800,41.4400,41.07,NaN,NaN,NaN,NaN,NaN
305049,2021-07-12 19:12:00,41.5600,41.590,41.5500,41.5500,1973,[],41.5300,41.6200,41.5700,41.4100,41.19,NaN,NaN,NaN,NaN,NaN
305050,2021-07-12 19:13:00,41.5400,41.540,41.5300,41.5300,1073,[],41.6200,41.6700,41.5700,41.4500,41.05,NaN,NaN,NaN,NaN,NaN
305051,2021-07-12 19:14:00,41.5200,41.620,41.5200,41.6200,2984,[],41.6700,41.5800,41.5800,41.4500,41.08,NaN,NaN,NaN,NaN,NaN
305052,2021-07-12 19:15:00,41.6700,41.670,41.6500,41.6700,1687,[],41.5800,41.5700,41.5501,41.4000,41.10,NaN,NaN,NaN,NaN,NaN
305053,2021-07-12 19:16:00,41.6500,41.670,41.5800,41.5800,4900,[],41.5700,41.5700,41.5600,41.3600,41.01,NaN,NaN,NaN,NaN,NaN
305054,2021-07-12 19:17:00,41.5500,41.570,41.5200,41.5700,3054,[],41.5700,41.5800,41.5500,41.3700,41.02,NaN,NaN,NaN,NaN,NaN
305055,2021-07-12 19:18:00,41.5500,41.590,41.5300,41.5700,1497,[],41.5800,41.5501,41.5400,41.4200,41.03,NaN,NaN,NaN,NaN,NaN
305056,2021-07-12 19:19:00,41.5700,41.580,41.5700,41.5800,14720,[],41.5501,41.5600,41.5200,41.4000,41.02,NaN,NaN,NaN,NaN,NaN
305057,2021-07-12 19:20:00,41.5700,41.570,41.5500,41.5501,1460,[],41.5600,41.5500,41.5200,41.4100,41.02,NaN,NaN,NaN,NaN,NaN
305058,2021-07-12 19:21:00,41.5500,41.570,41.5500,41.5600,4725,[],41.5500,41.5400,41.4400,41.3900,41.20,NaN,NaN,NaN,NaN,NaN
305059,2021-07-12 19:22:00,41.5700,41.570,41.5200,41.5500,6234,[],41.5400,41.5200,41.4100,41.3500,41.19,NaN,NaN,NaN,NaN,NaN
305060,2021-07-12 19:23:00,41.5300,41.540,41.5200,41.5400,2945,[],41.5200,41.5200,41.4500,41.3200,41.15,NaN,NaN,NaN,NaN,NaN
305061,2021-07-12 19:24:00,41.5400,41.540,41.5200,41.5200,8929,[],41.5200,41.4400,41.4500,41.2500,41.23,NaN,NaN,NaN,NaN,NaN
305062,2021-07-12 19:25:00,41.5200,41.530,41.5100,41.5200,3740,[],41.4400,41.4100,41.4000,41.1601,41.22,NaN,NaN,NaN,NaN,NaN
305063,2021-07-12 19:26:00,41.5100,41.510,41.4000,41.4400,23944,[],41.4100,41.4500,41.3600,41.0700,41.29,NaN,NaN,NaN,NaN,NaN
305064,2021-07-12 19:27:00,41.4400,41.440,41.3500,41.4100,14008,[],41.4500,41.4500,41.3700,41.1900,41.33,NaN,NaN,NaN,NaN,NaN
305065,2021-07-12 19:28:00,41.4101,41.490,41.4101,41.4500,6497,[],41.4500,41.4000,41.4200,41.0500,41.25,NaN,NaN,NaN,NaN,NaN
305066,2021-07-12 19:29:00,41.4800,41.480,41.4500,41.4500,4585,[],41.4000,41.3600,41.4000,41.0800,41.25,NaN,NaN,NaN,NaN,NaN
305067,2021-07-12 19:30:00,41.4200,41.450,41.4000,41.4000,5933,[],41.3600,41.3700,41.4100,41.1000,41.28,NaN,NaN,NaN,NaN,NaN
305068,2021-07-12 19:31:00,41.3700,41.400,41.3600,41.3600,4045,[],41.3700,41.4200,41.3900,41.0100,NaN,NaN,NaN,NaN,NaN,NaN
305069,2021-07-12 19:32:00,41.3600,41.400,41.3600,41.3700,4106,[],41.4200,41.4000,41.3500,41.0200,NaN,NaN,NaN,NaN,NaN,NaN
305070,2021-07-12 19:33:00,41.3900,41.420,41.3700,41.4200,4907,[],41.4000,41.4100,41.3200,41.0300,NaN,NaN,NaN,NaN,NaN,NaN
305071,2021-07-12 19:34:00,41.4210,41.421,41.3800,41.4000,8350,[],41.4100,41.3900,41.2500,41.0200,NaN,NaN,NaN,NaN,NaN,NaN
305072,2021-07-12 19:35:00,41.4000,41.450,41.4000,41.4100,5311,[],41.3900,41.3500,41.1601,41.0200,NaN,NaN,NaN,NaN,NaN,NaN
305073,2021-07-12 19:36:00,41.4000,41.400,41.3700,41.3900,3452,[],41.3500,41.3200,41.0700,41.2000,NaN,NaN,NaN,NaN,NaN,NaN
305074,2021-07-12 19:37:00,41.3800,41.390,41.3500,41.3500,6707,[],41.3200,41.2500,41.1900,41.1900,NaN,NaN,NaN,NaN,NaN,NaN
305075,2021-07-12 19:38:00,41.3500,41.350,41.2500,41.3200,7675,[],41.2500,41.1601,41.0500,41.1500,NaN,NaN,NaN,NaN,NaN,NaN
305076,2021-07-12 19:39:00,41.3000,41.310,41.2500,41.2500,10986,[],41.1601,41.0700,41.0800,41.2300,NaN,NaN,NaN,NaN,NaN,NaN
305077,2021-07-12 19:40:00,41.2900,41.290,41.1601,41.1601,7499,[],41.0700,41.1900,41.1000,41.2200,NaN,NaN,NaN,NaN,NaN,NaN
305078,2021-07-12 19:41:00,41.1800,41.180,41.0500,41.0700,15683,[],41.1900,41.0500,41.0100,41.2900,NaN,NaN,NaN,NaN,NaN,NaN
305079,2021-07-12 19:42:00,41.0500,41.190,41.0500,41.1900,23655,[],41.0500,41.0800,41.0200,41.3300,NaN,NaN,NaN,NaN,NaN,NaN
305080,2021-07-12 19:43:00,41.1900,41.190,41.0500,41.0500,9346,[],41.0800,41.1000,41.0300,41.2500,NaN,NaN,NaN,NaN,NaN,NaN
305081,2021-07-12 19:44:00,41.0500,41.100,41.0500,41.0800,9082,[],41.1000,41.0100,41.0200,41.2500,NaN,NaN,NaN,NaN,NaN,NaN
305082,2021-07-12 19:45:00,41.0700,41.100,41.0000,41.1000,24459,[],41.0100,41.0200,41.0200,41.2800,NaN,NaN,NaN,NaN,NaN,NaN
305083,2021-07-12 19:46:00,41.1000,41.100,41.0100,41.0100,9780,[],41.0200,41.0300,41.2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305084,2021-07-12 19:47:00,41.0100,41.050,41.0000,41.0200,8506,[],41.0300,41.0200,41.1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305085,2021-07-12 19:48:00,41.0300,41.030,41.0100,41.0300,3359,[],41.0200,41.0200,41.1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305086,2021-07-12 19:49:00,41.0300,41.030,41.0000,41.0200,37562,[],41.0200,41.2000,41.2300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305087,2021-07-12 19:50:00,41.0200,41.070,41.0100,41.0200,17505,[],41.2000,41.1900,41.2200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305088,2021-07-12 19:51:00,41.0600,41.200,41.0600,41.2000,11010,[],41.1900,41.1500,41.2900,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305089,2021-07-12 19:52:00,41.1500,41.280,41.1500,41.1900,7237,[],41.1500,41.2300,41.3300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305090,2021-07-12 19:53:00,41.1900,41.200,41.1500,41.1500,8237,[],41.2300,41.2200,41.2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305091,2021-07-12 19:54:00,41.1600,41.230,41.1000,41.2300,13137,[],41.2200,41.2900,41.2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305092,2021-07-12 19:55:00,41.2500,41.270,41.2200,41.2200,5550,[],41.2900,41.3300,41.2800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305093,2021-07-12 19:56:00,41.2500,41.290,41.2200,41.2900,10274,[],41.3300,41.2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305094,2021-07-12 19:57:00,41.2700,41.350,41.2500,41.3300,6832,[],41.2500,41.2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305095,2021-07-12 19:58:00,41.3300,41.330,41.2500,41.2500,14056,[],41.2500,41.2800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305096,2021-07-12 19:59:00,41.2500,41.280,41.2500,41.2500,8974,[],41.2800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305097,2021-07-12 20:00:00,41.2500,41.340,41.2500,41.2800,11989,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
f1.head(50)

,time,open,high,low,close,volume,token,close_1,close_2,close_5,close_15,close_30,close_60,close_180,close_450,close_1440,close_2880
0,2019-07-24 09:00:00,4.090000,4.090000,4.090000,4.090000,406,"['index', 'fund', 'tracks', 'performance', 'st...",9.912903,9.922435,9.951029,10.058260,10.232213,10.065409,10.213149,10.356505,10.780282,3.990000
1,2019-07-24 09:31:00,9.846181,9.912903,9.846181,9.912903,23448,[],9.922435,9.998688,10.037386,4.145000,10.260808,10.070175,10.220012,10.356124,4.105000,10.675434
2,2019-07-24 09:32:00,9.922435,9.951029,9.922435,9.922435,3394,[],9.998688,9.960561,10.103536,10.074941,10.275010,10.103536,10.206859,10.360890,10.791339,10.675434
3,2019-07-24 09:33:00,9.939591,9.998688,9.935302,9.998688,24294,[],9.960561,9.951029,10.103536,10.041580,10.284637,4.155000,10.213149,10.356124,10.794579,10.742155
4,2019-07-24 09:34:00,10.003453,10.017751,9.874776,9.960561,67195,[],9.951029,10.037386,10.046346,10.098770,10.298934,10.113067,10.217915,10.356124,10.785048,10.742155
5,2019-07-24 09:35:00,9.968758,9.979624,9.951029,9.951029,1734,[],10.037386,10.103536,10.065409,10.151194,10.332295,10.117833,10.236979,4.200000,10.780282,3.880000
6,2019-07-24 09:36:00,9.955795,10.037386,9.951029,10.037386,21448,[],10.103536,10.103536,10.078753,10.198852,10.322763,4.155000,10.232213,10.341827,10.780282,10.675624
7,2019-07-24 09:37:00,10.055877,10.103536,10.055877,10.103536,22069,[],10.103536,10.046346,10.091430,4.120000,10.360890,10.103536,10.217915,10.294168,10.761219,10.684966
8,2019-07-24 09:38:00,10.093813,10.103536,10.084472,10.103536,9494,[],10.046346,10.065409,10.070175,10.208384,10.351358,10.106967,4.105000,4.230000,10.756453,10.675434
9,2019-07-24 09:39:00,10.098770,10.098770,10.036814,10.046346,10919,[],10.065409,10.078753,4.140000,10.198852,10.337061,10.098770,10.246510,10.341731,10.756453,10.675434
10,2019-07-24 09:40:00,10.055877,10.084472,10.036814,10.065409,5081,[],10.078753,10.091430,10.058260,10.203618,10.303605,10.108111,10.241744,10.337061,10.751687,10.723092
11,2019-07-24 09:41:00,10.065409,10.094099,10.065409,10.078753,9733,[],10.091430,10.070175,4.145000,10.189320,10.275105,10.103536,10.246510,4.200000,10.751687,10.675434
12,2019-07-24 09:42:00,10.094004,10.122599,10.069889,10.091430,32169,[],10.070175,4.140000,10.074941,10.236979,10.198852,10.094004,10.246510,10.341827,10.761219,10.713560
13,2019-07-24 09:43:00,10.094004,10.113067,10.065409,10.070175,5716,[],4.140000,10.058260,10.041580,10.241744,10.198566,10.103536,10.246510,10.332295,10.751687,3.860000
14,2019-07-24 09:44:00,4.140000,4.140100,4.140000,4.140000,1209,"['makes', 'sense', 'thank', 'that', 'still', '...",10.058260,4.145000,10.098770,10.246510,10.189320,10.084472,10.241744,4.210000,4.120000,10.913725
15,2019-07-24 09:45:00,10.046346,10.074941,10.036814,10.058260,12005,[],4.145000,10.074941,10.151194,10.232213,10.122599,4.150000,10.241744,4.220000,10.742155,10.856535
16,2019-07-24 09:46:00,4.145000,4.150000,4.140000,4.145000,6709,"['bought', 'anything', 'recently', 'only', 'th...",10.074941,10.041580,10.198852,10.260808,4.160000,10.094004,10.236979,10.332295,10.761219,10.894662
17,2019-07-24 09:47:00,10.094004,10.103536,10.065409,10.074941,11129,[],10.041580,10.098770,4.120000,10.275010,10.132131,10.102582,10.236979,10.317997,10.765984,10.932788
18,2019-07-24 09:48:00,10.065409,10.065409,10.041580,10.041580,1543,[],10.098770,10.151194,10.208384,10.284637,4.154500,10.098770,10.232213,10.324956,10.770750,11.051934
19,2019-07-24 09:49:00,10.054066,10.103536,10.054066,10.098770,18979,[],10.151194,10.198852,10.198852,10.298934,10.179789,10.098770,10.232213,10.303700,10.779996,11.085390
20,2019-07-24 09:50:00,10.103536,10.189320,10.103536,10.151194,34947,[],10.198852,4.120000,10.203618,10.332295,10.198852,10.103440,10.236025,4.215000,10.761219,11.028104
21,2019-07-24 09:51:00,10.160725,10.198852,10.160725,10.198852,7834,[],4.120000,10.208384,10.189320,10.322763,10.151194,10.103536,10.232213,10.279204,10.775516,11.007040
22,2019-07-24 09:52:00,4.145000,4.145000,4.120000,4.120000,25399,"['believe', 'tsla', 'undervalued', 'due', 'mis...",10.208384,10.198852,10.236979,10.360890,10.175023,10.132131,10.222681,10.265573,10.775516,10.942320
23,2019-07-24 09:53:00,10.170257,10.208384,10.155960,10.208384,22320,[],10.198852,10.203618,10.241744,10.351358,10.132131,10.132131,10.236979,4.190000,10.770750,10.932788
24,2019-07-24 09:54:00,10.204571,10.227447,10.179789,10.198852,15144,[],10.203618,10.189320,10.246510,10.337061,10.151194,4.165000,10.217915,10.246510,10.770750,10.894662
25,2019-07-24 09:55:00,10.208384,10.217915,10.198852,10.203618,6276,[],10.189320,10.236979,10.232213,10.303605,10.151194,10.179789,10.213149,4.190000,10.770750,10.908959
26,2019-07-24 09:56:00,10.208002,10.213149,10.189320,10.189320,23620,[],10.236979,10.241744,10.260808,10.275105,4.160000,10.179789,4.106000,4.195000,10.761219,10.956617
27,2019-07-24 09:57:00,10.189320,10.246510,10.189320,10.236979,17638,[],10.241744,10.246510,10.275010,10.198852,4.160000,10.179789,10.203618,4.195000,10.766175,10.942320
28,2019-07-24 09:58:00,10.227447,10.241744,10.198852,10.241744,20656,[],10.246510,10.232213,10.284637,10.198566,4.160000,4.155000,4.100000,10.232213,10.765984,10.951851
29,2019-07-24 09:59:00,10.236979,10.246510,10.222681,10.246510,57024,[],10.232213,10.260808,10.298934,10.189320,10.073892,4.145000,4.105000,4.185000,10.761219,10.894662
30,2019-07-24 10:00:00,10.251276,10.260808,10.227447,10.232213,14466,[],10.260808,10.275010,10.332295,10.122599,10.065409,10.203618,10.189511,10.213149,4.110000,10.875598
31,2019-07-24 10:01:00,10.236979,10.270339,10.227828,10.260808,22732,[],10.275010,10.284637,10.322763,4.160000,10.070175,10.246510,10.194086,4.185000,10.761219,10.904193
32,2019-07-24 10:02:00,10.265573,10.289403,10.265573,10.275010,21485,[],10.284637,10.298934,10.360890,10.132131,10.103536,4.130000,10.194086,10.208384,4.100000,10.904193
33,2019-07-24 10:03:00,10.275105,10.284637,10.270339,10.284637,5030,[],10.298934,10.332295,10.351358,4.154500,4.155000,10.241744,4.100000,4.175000,10.751687,10.875598
34,2019-07-24 10:04:00,10.284637,10.298934,10.284637,10.298934,6987,[],10.332295,10.322763,10.337061,10.179789,10.113067,10.246510,10.175023,10.208384,10.765984,10.880364
35,2019-07-24 10:05:00,10.303700,10.346592,10.296837,10.332295,44281,[],10.322763,10.360890,10.303605,10.198852,10.117833,10.256042,10.189320,10.227352,10.761219,10.908959
36,2019-07-24 10:06:00,10.337061,10.337061,10.303700,10.322763,18423,[],10.360890,10.351358,10.275105,10.151194,4.155000,10.256042,4.105000,10.222681,10.784476,10.894662
37,2019-07-24 10:07:00,10.332295,10.360890,10.332295,10.360890,12291,[],10.351358,10.337061,10.198852,10.175023,10.103536,10.260808,10.184555,4.175000,10.780282,10.875598
38,2019-07-24 10:08:00,10.360890,10.379953,10.346592,10.351358,20668,[],10.337061,10.303605,10.198566,10.132131,10.106967,10.275105,10.184555,10.236979,10.770750,10.842238
39,2019-07-24 10:09:00,10.341827,10.351358,10.332295,10.337061,9296,[],10.303605,10.275105,10.189320,10.151194,10.098770,10.265573,4.100000,10.217915,10.770750,10.813643
40,2019-07-24 10:10:00,10.337537,10.337537,10.287877,10.303605,13509,[],10.275105,10.198852,10.122599,10.151194,10.108111,10.279871,10.187319,10.189320,10.770750,10.785048
41,2019-07-24 10:11:00,10.303700,10.308466,10.275105,10.275105,19150,[],10.198852,10.198566,4.160000,4.160000,10.103536,10.265478,10.179884,10.198852,4.100000,10.799345
42,2019-07-24 10:12:00,10.276058,10.276058,10.194086,10.198852,27988,[],10.198566,10.189320,10.132131,4.160000,10.094004,10.262047,10.198852,10.194086,10.761219,10.765984
43,2019-07-24 10:13:00,10.198852,10.208384,10.179789,10.198566,8165,[],10.189320,10.122599,4.154500,4.160000,10.103536,10.251276,10.194086,10.184555,10.765984,10.756453
44,2019-07-24 10:14:00,10.189320,10.194086,10.179789,10.189320,7134,[],10.122599,4.160000,10.179789,10.073892,10.084472,10.256042,10.198852,10.189320,10.785048,10.685728
45,2019-07-24 10:15:00,10.189320,10.189320,10.122599,10.122599,23855,[],4.160000,10.132131,10.198852,10.065409,4.150000,10.256042,10.194086,4.140000,10.780282,3.840000
46,2019-07-24 10:16:00,4.160000,4.160000,4.160000,4.160000,170,"['uhh', 'do', 'think', 'know', 'pilots', 'job'...",10.132131,4.154500,10.151194,10.070175,10.094004,10.265573,10.179693,10.198757,10.787431,10.713560
47,2019-07-24 10:17:00,10.141662,10.149955,10.103536,10.132131,12506,[],4.154500,10.179789,10.175023,10.103536,10.102582,10.270339,10.170257,10.189225,10.799345,10.713560
48,2019-07-24 10:18:00,4.154500,4.154500,4.154500,4.154500,407,"['gdp', 'goes', 'gdp', 'goes', 'principle', 'e...",10.179789,10.198852,10.132131,4.155000,10.098770,10.279871,10.160725,10.189320,10.803920,10.637307
49,2019-07-24 10:19:00,10.160725,10.198852,10.155960,10.179789,13255,[],10.198852,10.151194,10.151194,10.113067,10.098770,10.265573,10.160821,10.185508,10.804111,10.656371

In [79]:
#//*** Combine Columns
for col in df.columns:
    f1[col] = df[col]
    
#//*** Save File
training_filepath = './data/training_amc_1min.pkl.zip'

f1.to_pickle(training_filepath)
f1

,time,open,high,low,close,volume,token,close_1,close_2,close_5,...,91,92,93,94,95,96,97,98,99,y
0,2019-07-24 09:00:00,4.090000,4.090000,4.090000,4.090000,406,"['index', 'fund', 'tracks', 'performance', 'st...",9.912903,9.922435,9.951029,...,1.870481e-02,-4.346574e-02,-4.597366e-02,4.393613e-02,-1.982158e-02,3.886423e-03,-4.084313e-03,4.691091e-02,-4.536256e-02,-0.586013
1,2019-07-24 09:31:00,9.846181,9.912903,9.846181,9.912903,23448,[],9.922435,9.998688,10.037386,...,-3.622445e-15,2.604610e-15,3.638883e-15,-5.773362e-15,1.815679e-17,7.997190e-15,-8.216557e-16,4.425338e-15,5.004656e-15,-0.005040
2,2019-07-24 09:32:00,9.922435,9.951029,9.922435,9.922435,3394,[],9.998688,9.960561,10.103536,...,6.840537e-15,7.925148e-15,-6.897774e-15,5.217240e-15,9.536418e-15,1.094964e-15,6.264581e-15,5.849719e-15,8.439549e-15,-0.003861
3,2019-07-24 09:33:00,9.939591,9.998688,9.935302,9.998688,24294,[],9.960561,9.951029,10.103536,...,7.555619e-15,1.125621e-15,6.131435e-15,-8.294358e-15,2.983305e-15,2.607483e-14,8.351052e-15,-2.340860e-14,-1.577746e-14,0.000395
4,2019-07-24 09:34:00,10.003453,10.017751,9.874776,9.960561,67195,[],9.951029,10.037386,10.046346,...,1.553265e-17,-2.274470e-15,-5.351744e-16,-5.854387e-15,1.059291e-14,-9.265511e-16,5.714436e-15,-5.036118e-15,3.599688e-16,0.000153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305093,2021-07-12 19:56:00,41.250000,41.290000,41.220000,41.290000,10274,[],41.330000,41.250000,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,-0.000908
305094,2021-07-12 19:57:00,41.270000,41.350000,41.250000,41.330000,6832,[],41.250000,41.250000,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,0.000242
305095,2021-07-12 19:58:00,41.330000,41.330000,41.250000,41.250000,14056,[],41.250000,41.280000,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,0.000788
305096,2021-07-12 19:59:00,41.250000,41.280000,41.250000,41.250000,8974,[],41.280000,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,-0.000545
305097,2021-07-12 20:00:00,41.250000,41.340000,41.250000,41.280000,11989,[],NaN,NaN,NaN,...,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00,0.000000