In [1]:
# Packages
import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
import datetime
from All_data_muduo import df,f1
#//*** Use the whole window in the IPYNB editor
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

#//*** Maximize columns and rows displayed by pandas
# pd.set_option('display.max_rows', 1000)
# pd.set_option('display.max_columns',20 )

In [10]:
df["price"] = (f1["open"].values + f1["close"].values + f1["high"].values + f1["low"].values)/4

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,219005,219006,219007,219008,219009,219010,219011,219012,219013,price
time,,,,,,,,,,,,,,,,,,,,,
2019-07-24 09:00:00,0.0,0.052975,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.090000
2019-07-24 09:31:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.879542
2019-07-24 09:32:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.929583
2019-07-24 09:33:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.968067
2019-07-24 09:34:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.964135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-12 19:56:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.262500
2021-07-12 19:57:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.300000
2021-07-12 19:58:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.290000
2021-07-12 19:59:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.257500
2021-07-12 20:00:00,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.280000

In [22]:
'adding interval to each row'
intvs = [1,2,5,10,30,60,120,360,1440]


iterator = 0 # Don't over print

for Min in range(len(df)):
    iterator += 1 # Don't over print
    # Iterate over each comment in every minute
    for itv in intvs:
        futureMin = datetime.datetime(df.index[Min]datetime) + datetime.timedelta(0,itv)
        df[f"+{itv}m%Chg"][Min] = df[df.index == futureMin].open
        print(futureMin.index.hour)
        
        '''Add check for night-market close'''    
    
    
    if iterator > 5:
        break
        # Get price 1 minute in the future
        
#         print (df_by_minute.iloc[minute].features.iloc[single_comment].close) # Price @ comment time

SyntaxError: invalid syntax (<ipython-input-22-42f91407f158>, line 11)

In [ ]:
for row in range(len(df)):
    df["+1m%change"][row] = df.price[row+1] - df.price[row]